### ISSUE TITLE
Task: install pipenv

### ISSUE THREAD

**Issue by cseyda** [Kirchenchor/textadventure#8]
1. install [pipenv](https://pipenv.readthedocs.io/en/latest/)
2. get a small overview by quick reading https://pipenv.readthedocs.io/en/latest/basics/
you don't have to understand most stuff, but
- what this is useful for, and
- where you could read it

we will mostly just install, remove and upgrade python packages with it.

**Comment by cseyda** [comment]
any progress? @Acidburn707 @burningox

**Comment by Acidburn707** [comment]
Okay, done. Falls das Robin noch nicht erledigt hat: Grad nach der Anleitung für Windows gehen: https://www.linkedin.com/pulse/how-use-python-pipenv-mac-windows-mahmud-ahsan

**Comment by burningox** [comment]
Done. Hab ich auch mit dem Link gemacht.
